name: stormy_china_pay
description: "Stormy china_pay package"
version: 0.0.1
publish_to: none
resolution: workspace
environment:
  sdk: ^3.13.0
dependencies:
  fluwx: ^5.7.5
  stormy_core:
    path: ../stormy_core
  stormy_platform:
    path: ../stormy_platform
  tobias: ^5.3.4
dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
