name: stormy_kit
description: "Stormy kit package"
version: 1.1.0
publish_to: none
resolution: workspace
environment:
  sdk: ^3.13.0
dependencies:
  flutter:
    sdk: flutter
  stormy_core:
    path: ../stormy_core
  stormy_i18n:
    path: ../stormy_i18n
  stormy_platform:
    path: ../stormy_platform
  stormy_ui:
    path: ../stormy_ui
dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
